### ISSUE TITLE
Failed to run `til` after addting to `PATH`

### ISSUE THREAD

**Issue by PanZiwei** [danielecook/TIL-Tool#6]
Hi,
Thanks for the amazing tool for writing TIL.  I failed to run `til` and would really appreciate it if you can help on the issue.
Here is what I have done:
1. Download [til_macos-10.15](https://github.com/danielecook/TIL-Tool/releases/download/v0.0.3/til_macos-10.15) to my local machine, the path is `/Users/c-panz/Downloads/software/til_macos-10.15`.
2. Add the path in my `$HOME/.bashrc`, then save the file
```shell
export PATH="/Users/c-panz/.local/bin:$PATH"
export PATH="/Users/c-panz/Downloads/software/til_macos-10.15/bin:$PATH"
```
3. Restart my terminal.
4. Run `til`:
```shell
(base) MLG-JGM319:~ c-panz$ til
-bash: til: command not found
```

**Comment by danielecook** [comment]
Hi @PanZiwei you have to rename the binary. It currently is called `til_macos-10.15`

```bash
# You may also have to run chmod +x to allow for the binary to be executed.
chmod +x /Users/c-panz/Downloads/software/til_macos-10.15
mv /Users/c-panz/Downloads/software/til_macos-10.15 /Users/c-panz/.local/bin/til
export PATH="/Users/c-panz/.local/bin:$PATH"
```

**Comment by PanZiwei** [comment]
Hi @danielecook 
Thanks for the instruction. It seems it still failed with the following command:
```shell
(base) MLG-JGM319:software c-panz$ chmod +x /Users/c-panz/Downloads/software/til_macos-10.15
(base) MLG-JGM319:software c-panz$ mv /Users/c-panz/Downloads/software/til_macos-10.15 /Users/c-panz/.local/bin/til
(base) MLG-JGM319:software c-panz$ cd /Users/c-panz/.local/bin/
(base) MLG-JGM319:bin c-panz$ ls
__pycache__	globus		jp.py		pyjwt		til
(base) MLG-JGM319:bin c-panz$ til
-bash: til: command not found
(base) MLG-JGM319:bin c-panz$ export PATH="Users/c-panz/.local/bin:$PATH"
(base) MLG-JGM319:bin c-panz$ til
-bash: til: command not found
```

**Comment by danielecook** [comment]
Can you confirm the binary is located in that directory with ls?

**Comment by PanZiwei** [comment]
Yes it's there...
```shell
(base) MLG-JGM319:~ c-panz$ ls /Users/c-panz/.local/bin
__pycache__	globus		jp.py		pyjwt		til
```

**Comment by danielecook** [comment]
Can you also access 'globus'?

Run this and try again:

```

export PATH="/Users/c-panz/.local/bin:$PATH"

```

It looks like you may have forgotten the leading slash?
